# MUST EDIT BELOW
sitename: 유스풀패러다임       #Your site title
tagline: Web 2.0 Software Service & Solutions  #You should always have a tagline
url: http://usefulparadigm.com   #URL Please
ga: UA-16954113-1              #Google Analytics ID
sitemap: KyE-PMrb9__CwHMsFc2fM_b1ecWeTs3P5SKZwvcFTaA    #Google webmaster verification code
# END
# CHOOSE YOUR PREFERENCE
pygments:    true
markdown:    maruku
permalink:   pretty
# END
exclude: LICENSE, README.markdown, Rakefile, Gemfile, Gemfile.lock, CNAME
