# MUST EDIT BELOW
sitename: Useful Paradigm       #Your site title
tagline: Web 2.0 Services & Solutions  #You should always have a tagline
url: http://usefulparadigm.com   #URL Please
ga: UA-XXXXX-X              #Google Analytics ID
sitemap: GOOGLEWEBMASTER    #Google webmaster verification code
# END
# CHOOSE YOUR PREFERENCE
pygments:    true
markdown:    maruku
permalink:   pretty
# END
exclude: LICENSE, README.markdown, Rakefile
