# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title 
permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
auto: true
markdown: kramdown
safe: true
pygments: true
lsi: false

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
url: http://usefulparadigm.com
title: 유스풀패러다임
tagline: We think, work, and create on Web #Yet Another Software Factory on Web
author:
  name: Useful Paradigm
  email: contact@usefulparadigm.com
  github: usefulparadigm
  twitter: usefulparadigm
  facebook: usefulparadigm.soft
  googleplus: 115107364790115869238
  feedburner : feedname

